# Creo una lista de cuadrados de nros del 0 al 4

cuadrados = [x**2 for x in range(5)]
print(cuadrados)

# PONGO RANGE(5) COMO ITERABLE PARA QUE VAYA DEL 0 AL 4
# X TOMA CADA UNO DE LOS VALORES DEL RANGE(5) E ITERA
# X**2 ES EL NUEVO VALOR A APLICAR EN CADA ITERACION. LE DIGO QUE CALCULE LA POTENCIA DE CADA ITERABLE
# EL RESULTADO ES UNA NUEVA LISTA LLAMADA CUADRADOS

# Si quiero filtar elementos:

# Crear una lista con nros del 0 al 9:
pares = [x for x in range(10) if x % 2 == 0]
print(pares)

# PONGO RANGE(10) COMO ITERABLE PARA QUE VAYA DEL 0 AL 9
# FOR 'X' ACA X TOMA EL VALOR DE CADA UNO DE LOS ITERABLES DEL 0 AL 9
# 'IF X % 2 == 0' ES UNA CONDICION DE FILTRO, SOLO DEVUELVE LOS PARES
# 'X' AL PRINCIPIO ES EL VALOR QUE SE AGREGA A LA NUEVA LISTA SOLO SI SE CUMPLE LA CONDICION O SEA SI ES PAR
